#!/usr/bin/env zsh

# Git clone
cd ~/Desktop
/bin/rm -rf .git
/usr/local/bin/git init
/usr/local/bin/git remote add origin https://github.com/cgerke/dots
/usr/local/bin/git fetch --all --prune
/usr/local/bin/git checkout master

# Symlink dot files
for i in ".ssh" ".vim" ".gitconfig" ".gitmessage" ".vimrc" ".zshrc"
do
	/bin/rm -f ~/${i}
	/bin/ln -fs ~/Desktop/${i} ~/${i}
done

exit 0
